### ISSUE TITLE
ブログ記事を評価する基準

### ISSUE THREAD

**Issue by pokohide** [OthloTech/OthloTech#117]
http://web-tan.forum.impressrd.jp/e/2015/01/05/19010
http://www.ginzametrics.jp/blog/metrics-for-media-content-and-content-engagement

**Comment by ryosism** [comment]
多少修正しましたがひとまずこれで確定します！
4半期終わったらバランスまた考える感じで。

|名前|イベントアクション名|点数|
|:---|:---|:---|
|ページビュー(リロードごと)|pageview|1|
|Facebookでのシェア|fb_share|15|
|Twitterでのリンク付きツイート|tw_share|5|
|Google+でのリンク付き投稿|plus|5|
|はてブでのリンク付き投稿|hb_share|5|
