### ISSUE TITLE
記事内の画像のサイズは80%くらいにしたい

### ISSUE THREAD

**Issue by haseaki0503** [OthloTech/OthloTech#124]
記事内の画像のサイズをもう少し小さくしたほうが読みやすい気がする

**Comment by pokohide** [comment]
@haseaki0503 

cssで
```
.post-content {
  figure > img {
    width: 80%;
  }
}
```

で多分適用できそう！
ただスマホサイズの時に80%だと逆に小さいきがしたから、メディアクエリでスマホサイズの場合はwidth: 100%でいこう！

多分CSSいじるだけでいけるからお願いしたい！

**Comment by haseaki0503** [comment]
見やすいデザインを考える必要がありそうなので、どうしたら見やすいのかデザイナーで話し合ったほうが良さそうです。別のIsssueでまとめます。
