### ISSUE TITLE
オスロ運営メンバーにOBタグを導入する

### ISSUE THREAD

**Issue by pokohide** [OthloTech/OthloTech#135]
memberにob=trueとfalseをいれる。
あと、学年も入れれたら入れる

**Comment by haseaki0503** [comment]
@hyde2able OBと現役と混在させるか、それぞれ分けてOBはOBだけ表示させるかどちらが良いでしょう？

**Comment by pokohide** [comment]
@haseaki0503 

今も今後もmembersディレクトリに現役メンバーを、obogsディレクトリに引退メンバーをみたいに作ったほうが良さそうだね！ob=trueみたいなフラッグ持たせるよりも！

obogsは名前何か任せる（笑）　retired_membersでもいい誌！

それで、今のmembersをループさせて表示させてるように、現役メンバーの下に、OB/OGってヘッダーつけて、引退メンバーもループして表示させる感じ！
画像とか文字とか表示するのは一緒でいいと思う！デザインとかは
