### ISSUE TITLE
画像の保管場所

### ISSUE THREAD

**Issue by pokohide** [OthloTech/OthloTech#14]
メンバー画像とかくらいなら正直いいけど、イベント画像はイベントレポート1つに対して5,6枚とかの画像を今後使っていくと考えると、画像の縮小とかはするにしてもなかなか容量が食ってくると思う。

案
- まぁいんじゃね?
- `images` ブランチに画像を格納(容量は減らない)
- 他のサービスに画像を乗せる
- 画像を非同期ロード

**Comment by iyuto** [comment]
@hyde2able とりあえず今のままでいいんじゃない！
ただ画像1枚100KB以下に収めるとかルール決めたほうがいいかもね。

**Comment by pokohide** [comment]
@iyuto githubの容量(cloneした時の)とかをきにするレベルになったら `firebase` の `storage` にいれて非同期とか問題になってから考えよっか

画像の非同期ロードだけ簡単だしまた、実装するわー
https://github.com/tuupola/jquery_lazyload

**Comment by iyuto** [comment]
@hyde2able `image`の`shortcodes`いじれば移行は簡単そう。
ただストレージに画像ファイル移行してもリポジトリの容量は減らない問題はあるw
