### ISSUE TITLE
gulpのバージョンが古くてscssのコンパイルでエラーが発生する

### ISSUE THREAD

**Issue by Juju-62q** [OthloTech/OthloTech#184]
アップデートしてもいいんじゃないかな？

**Comment by Juju-62q** [comment]
一度ミスってグローバルインストールしたあと実行したらエラーがなくなった。
自分の環境ではnpmはほとんどいじってなかったから環境によるのかもしれない。
とりあえず放置して良いかも。

**Comment by yoshikawa** [comment]
【開発環境】
node v9.3.0
 npm v5.8.0

【僕がやったこと】
npm自身のアップデート
```
npm i -g npm
```
npm-check-updatesをインストール
```
npm i -g npm-check-updates
```
npm-check-updates(ncu)を用いて、パッケージにアップデートがあるか確認
```
ncu
```
ncuが、package.jsonを書き換えてくれるコマンド
```
ncu -u
```
パッケージのインストール
```
npm install
```
