### ISSUE TITLE
イベントレポートとか記事ごとにOGP変える

### ISSUE THREAD

**Issue by pokohide** [OthloTech/OthloTech#30]
`hugo` だとどうやってやるんだろ(´･ω･`)

でも、これやらないとイベントレポートシェアしてもあれだしなぁ。早めにやろっと

http://qiita.com/y_hokkey/items/f9d8b66b3770a82d4c1c#%E3%83%A1%E3%82%BF%E6%83%85%E5%A0%B1
ここを参考に

**Comment by iyuto** [comment]
@hyde2able 
`ogp.html`で普通に`{{ .Params.hoge }}`とかでポスト毎の変数取れたよ〜
