### ISSUE TITLE
ブロクポストのドキュメントを作る

### ISSUE THREAD

**Issue by iyuto** [OthloTech/OthloTech#38]
ブログ記事書くときの決まり。
- カテゴリやタグの決め方
- 見出しタイトル
- slugの命名規則
- 画像サイズ
- その他校正とか

**Comment by pokohide** [comment]
一応、投稿の手順は `post.md` (https://github.com/OthloTech/OthloTech/blob/master/post.md) ここにまとめてもらえると嬉しい。

**Comment by iyuto** [comment]
#86 でマージ。
ドキュメントは適時追加修正していくかんじで。
