### ISSUE TITLE
メンバーページがモバイルで表示崩れる

### ISSUE THREAD

**Issue by iyuto** [OthloTech/OthloTech#43]
スマホだと表示崩れる。スキルセットとSNSのアイコンを`いい感じ`にコンパクトにしたい！
（メンバーの画像こんなに大きくなくていいから2列にしたいなぁ...）

![2016-10-25 23 52 59](https://cloud.githubusercontent.com/assets/6602987/19691175/4ac6954a-9b0e-11e6-8f76-fa95a8ca0917.png)

**Comment by haseaki0503** [comment]
c50a43a で `.othlo-member`のheightプロパティ削除、`.member-text`のheightプロパティをmin-heightプロパティに変更。
f32ca73で`.member-text`の高さをmatchHeight。

**Comment by iyuto** [comment]
#45 でマージ
