### ISSUE TITLE
Events以下のサイト構造

### ISSUE THREAD

**Issue by haseaki0503** [OthloTech/OthloTech#58]
技術ブログがEventsのCategoryに含まれてますが、技術ブログは今後navbarに追加されますか？
あと、カテゴリのリンク先が謎...

![2016-11-02 13 08 24](https://cloud.githubusercontent.com/assets/5466652/19916526/108c47ee-a0fe-11e6-8c93-3eb4dc7d7715.png)

**Comment by iyuto** [comment]
@haseaki0503 
#60 でBLOGを`navbar`に追加したんだけど、`/events`と`/blog`でカテゴリ・タグが共有されてて、しかもクリックしても`/events`のカテゴリとタグが参照できてないんだよね。
Hugoのテンプレの問題かなー

**Comment by iyuto** [comment]
#70 と #81 で解決したかなー
