### ISSUE TITLE
navbarの追従でカクつく

### ISSUE THREAD

**Issue by iyuto** [OthloTech/OthloTech#6]
Chromeはまだマシだけど、Safariで特に。
![laggy](https://cloud.githubusercontent.com/assets/6602987/19416401/32a5113a-93ca-11e6-94ca-5bfd16888f6e.gif)

**Comment by pokohide** [comment]
現状だと追従みたいな感じになってるけど、下記のサイトみたいにもう固定にしちゃいますか。

https://www.cyberagent.co.jp/recruit/fresh/real/event_detail/id=12607

**Comment by iyuto** [comment]
シンプルで良いと思う！
