### ISSUE TITLE
タグを全件表示しない

### ISSUE THREAD

**Issue by pokohide** [OthloTech/OthloTech#65]
ブログのサイドバーでタグを全件表示しているが、これを最大7件くらいにしたい。
やってみたけど、かなり難しそう。めんどくさそう。変える行数は1行なんだけど、ちゃんと理解しないといけなさそうなので、一旦ISSUE化

`layouts/widgets/tags.html` と `layouts/widgets/categories.html` を編集する

https://discuss.gohugo.io/t/how-to-conditionally-apply-html-code-after-every-3-posts/3118
https://discuss.gohugo.io/t/attaching-an-index-to-a-range/1792/2

このあたりを参照？

https://discuss.gohugo.io/search?q=range%20first

**Comment by iyuto** [comment]
@hyde2able これってもう閉じてOK？

**Comment by pokohide** [comment]
@iyuto いやーまだ実装してない！これは面倒くさそう
