### ISSUE TITLE
記事のタグ・カテゴリ・階層名について

### ISSUE THREAD

**Issue by iyuto** [OthloTech/OthloTech#70]
### 現状
- 記事は`/events`と`/posts`の二種類
- それぞれのタグとカテゴリは別々に管理

### 提案1
- ディレクトリ名を`/posts`→`/blogs`に変更
  - 記事は`/events`と`/blogs`の二種類
- `/events`のカテゴリを廃止

### 提案2
- 記事はイベントレポもブログも`/posts`に集約
  - タグ・カテゴリを共有
- ナビゲーションの`EVENTS`は`/categories/events`へリンクさせる

**Comment by pokohide** [comment]
提案1採用。やりますー！
- `/posts` → `/blogs`
- `event_categories` 廃止

**Comment by mtmtkzm** [comment]
@iyuto @hyde2able 
もう終わっちゃってたりしたらもういいんだけど、blog+sって違和感ない？文字に起こすとちょっと目に付いた😅

**Comment by iyuto** [comment]
確かに気になる...
`blog`にするなら`events`も`event`にしたいね。

**Comment by pokohide** [comment]
@mtmtkzm @iyuto 

`blogs`, `events` に統制しちゃう！
なんか、いい命名が思いつかないから。

`blog` にすると、単数系に結局困って、`blog` 内の記事を `post` って呼ぶことにすると統一感ないし、なら `blogs` とした方がいいなと感じたからこのままいきますー！

PR立ててレビュー待ちだから、レビューお願いしますー！

**Comment by iyuto** [comment]
@mtmtkzm  @hyde2able 今色々弄ってるけど、hugoの仕様的に`blogs`にしたほうがよさそうだね。
`SINGULAR`と`PLURAL`でファイルの命名規則決まってるらしい。

**Comment by pokohide** [comment]
閉じるねー！ #81 で対応。
