### ISSUE TITLE
日本語のカテゴリ/タグはURLでは英語表記にしたいよね...

### ISSUE THREAD

**Issue by iyuto** [OthloTech/OthloTech#71]

**Comment by pokohide** [comment]
今までのについては一気に一つのPRで変えることにして、それ以降はこのIssue同様、しっかりドキュメントに沿って書いてもらうようにすれば解決しそうだね。
またPR立てて作業しますかー

https://github.com/OthloTech/OthloTech/issues/38

**Comment by iyuto** [comment]
これHugoの仕様的に無理そう。

**Comment by pokohide** [comment]
タグは無理やね！

**Comment by iyuto** [comment]
@hyde2able カテゴリはいける？

**Comment by pokohide** [comment]
@iyuto 同じく無理だね。`taxinomy` の仕様的に。つづり違うかも

**Comment by pokohide** [comment]
これ無理そうだから閉じますか。
