### ISSUE TITLE
ショートコード {{< link src='URL' >}} とかではてなブログのカード的なもの出したい

### ISSUE THREAD

**Issue by otomore** [OthloTech/OthloTech#72]
![2016-11-08 13 10 48](https://cloud.githubusercontent.com/assets/15990825/20089935/606432d0-a5cd-11e6-9753-d59d100253fb.png)

**Comment by pokohide** [comment]
https://www.lecarra-orica.com/2016/08/playing-with-hugo-shortcodes/
