### ISSUE TITLE
メンバー一覧をちゃんとする。

### ISSUE THREAD

**Issue by pokohide** [OthloTech/OthloTech#8]
メンバーの使用言語なども聞くー

使用言語はここを参考に
http://vorillaz.github.io/devicons/#/cheat
- [x] ひで
- [x] 矢崎
- [x] ライダー
- [x] ごまき
- [x] やっさん
- [x] かみわだ
- [x] マスカット
- [x] はせあき
- [x] terabyte
- [x] OTMOREee
- [x] たつま
- [x] にーさん

**Comment by iyuto** [comment]
スキルアイコンもうちょっと大きくしたい。色つけるのはめんどくさそうw

**Comment by Tattsum** [comment]
terabytesさんのプロフィール追加したんで、レビューお願いします。
