### ISSUE TITLE
ブログ記事の画像がはみ出る件

### ISSUE THREAD

**Issue by pokohide** [OthloTech/OthloTech#82]
![2016-11-12 4 19 20](https://cloud.githubusercontent.com/assets/11733664/20227455/ad0a9592-a88f-11e6-8a5b-a1cfa203004b.png)

こんな感じになぜかはみ出る。

#blog-postにうまくスタイルが当たってないので、修正。これは早めに対応すること。

**Comment by mtmtkzm** [comment]
@hyde2able 閉じていいかなーー？？

**Comment by iyuto** [comment]
#83
