### ISSUE TITLE
スマホサイトにした時の謎の余白解消

### ISSUE THREAD

**Issue by pokohide** [OthloTech/OthloTech#89]
http://on-ze.com/archives/1902
http://koukitips.net/responsive-enigma-blank/
http://bashalog.c-brains.jp/15/06/26-170500.php

このあたりで対応できるはず。

**Comment by haseaki0503** [comment]
@hyde2able その現象確認できません、、、どのページですか？

**Comment by pokohide** [comment]
<img width="607" alt="2017-03-10 19 25 45" src="https://cloud.githubusercontent.com/assets/11733664/23791701/676dec42-05c7-11e7-9cf8-fdba12ceb2f2.png">

PCでスマホサイズで確認したら、右に余白あってあれ？ってなったけど、スマホから確認したらなんともなかったわー何だろこの差

**Comment by haseaki0503** [comment]
javascriptで横幅設定してるなら、なんとなく横幅を計算するタイミングとかありそう
