### ISSUE TITLE
テーブルのスクロールバー

### ISSUE THREAD

**Issue by occar421** [OthloTech/OthloTech#93]
![table](https://cloud.githubusercontent.com/assets/3390557/20463537/97d835e0-af78-11e6-9292-941138603cb7.png)

ブログやイベント記事にて、幅は収まっているのに（動かない）スクロールバーが出てくる。
画像はChromeのものだが、VivaldiとEdgeでも確認。

Windows 10

**Comment by iyuto** [comment]
これ気になってた！
誰か直してくれ〜〜〜〜〜

(@mtmtkzm)

**Comment by pokohide** [comment]
原因なんだろうね。ブラウザの問題かな？
自分で趣味レベルで作ってるとブラウザ間の問題とかあんまり気にしないから勉強になりそう

今度LTそういうのでしたいなー。
javascriptの`blur`の挙動とかブラウザで違ったりするから難しい問題だよね。IEはあかん

**Comment by iyuto** [comment]
どのブラウザでもスクロールバー表示されるから、ブラウザ依存ではなさそう？

というか、ここを`overflow: auto;`したら普通に直ったw
https://github.com/OthloTech/OthloTech/pull/83/files#diff-722103e3c3779b17720145bf4ec3741dR96

**Comment by occar421** [comment]
Windows10でChrome, Vivaldi, Edgeで確認👌  
Windowsだけの問題じゃなかったのね～
